### ISSUE TITLE
undefined method `match?'

### ISSUE THREAD

**Issue by jimmynguyc** [teohm/git-chlog#6]
I'm getting this error :-

`exe/git-chlog:29:in `matching_repo_url?': undefined method `match?' for /github\.com/:Regexp (NoMethodError)`

**Comment by teohm** [comment]
@jimmynguyc looks like `Regexp#match?` is only available in Ruby 2.4. I'll change it to make it compatible with older ruby versions

**Comment by teohm** [comment]
@jimmynguyc fyi, this is fixed in new patch release: v0.2.1. try it out! 👀

**Comment by jimmynguyc** [comment]
Works !! 👍
